repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.2.2
    hooks:
      - id: ruff
        args: [--no-fix]
        exclude: ^\.history/
      - id: ruff-format
        args: [--check]
        exclude: ^\.history/

  - repo: local
    hooks:
      - id: check-for-changes
        name: Check for unexpected changes
        entry: bash -c 'git diff --exit-code'
        language: system
        types: [python]
        exclude: ^\.history/
        pass_filenames: false
        always_run: true
