site_name: MermaidMD2PDF
site_description: Convert Markdown files with Mermaid diagrams to PDF
repo_url: https://github.com/chadrwalters/MermaidMD2PDF
theme:
  name: material
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.suggest
    - search.highlight

nav:
  - Home: index.md
  - User Guide: user-guide/README.md
  - API Reference:
      - Overview: api-reference/README.md
      - Examples: api-reference/examples.md
  - Examples:
      - Overview: examples/README.md
      - System Architecture: examples/system-architecture.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!str |
            <div class="mermaid">
            {content}
            </div>
  - admonition
  - footnotes
  - toc:
      permalink: true

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [src]
          options:
            show_source: true
            show_root_heading: true
