name: CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  release:
    types: [published]
  workflow_dispatch:

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Safety
        run: |
          python -m pip install safety
          safety check

  version:
    needs: [security]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install packaging

      - name: Validate versions
        run: |
          python scripts/validate_version.py

  test:
    needs: [security, version]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]
    env:
      PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: true
      CHROME_BIN: /usr/bin/chromium-browser
      PUPPETEER_EXECUTABLE_PATH: /usr/bin/chromium-browser
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc texlive-xetex librsvg2-bin chromium-browser

      - name: Install Node.js dependencies
        run: |
          npm ci
          sudo ln -s $(pwd)/node_modules/.bin/mmdc /usr/local/bin/mmdc
          mmdc --version

      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=$PYTHONPATH:${{ github.workspace }}/src" >> $GITHUB_ENV

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: |
            .venv
            ~/.cache/uv
          key: ${{ runner.os }}-python-${{ matrix.python-version }}-deps-${{ hashFiles('pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-python-${{ matrix.python-version }}-deps-

      - name: Debug environment
        run: |
          echo "Current directory: $(pwd)"
          echo "Directory contents:"
          ls -la
          echo "Python version:"
          python --version
          echo "PYTHONPATH: $PYTHONPATH"
          echo "Node.js version:"
          node --version
          echo "NPM version:"
          npm --version
          echo "Mermaid CLI version:"
          mmdc --version
        working-directory: ${{ github.workspace }}

      - name: Create virtual environment and install package
        run: |
          uv venv
          uv pip install -e .
        working-directory: ${{ github.workspace }}

      - name: Install test dependencies
        run: |
          uv pip install ".[dev]"
          uv pip install pytest-cov
        working-directory: ${{ github.workspace }}

      - name: Verify package installation
        run: |
          uv run python -c "import sys; print('Python path:', sys.path)"
          uv run python -c "import mermaidmd2pdf; print('Package found at:', mermaidmd2pdf.__file__)"
        working-directory: ${{ github.workspace }}

      - name: Run linters
        run: |
          uv run ruff check .
          uv run mypy src/
        working-directory: ${{ github.workspace }}

      - name: Run tests
        run: |
          uv run pytest -vl \
            --cov=mermaidmd2pdf \
            --cov-report=xml \
            --cov-report=term \
            tests/
        working-directory: ${{ github.workspace }}

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: false
        continue-on-error: true

  build:
    needs: [test, security, version]
    runs-on: ubuntu-latest
    if: github.event_name == 'release' && github.event.action == 'published'
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Create virtual environment and install build dependencies
        run: |
          uv venv
          uv pip install build twine
        working-directory: ${{ github.workspace }}

      - name: Build package
        run: |
          uv run python -m build
        working-directory: ${{ github.workspace }}

      - name: Publish to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          uv run twine upload dist/*
        working-directory: ${{ github.workspace }}
